# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('_QPADMslack_timesTwo', PACKAGE = 'QPADMslack', x)
}

sumArrayItems <- function(xa) {
    .Call('_QPADMslack_sumArrayItems', PACKAGE = 'QPADMslack', xa)
}

soloSumArrayItems <- function(xa) {
    .Call('_QPADMslack_soloSumArrayItems', PACKAGE = 'QPADMslack', xa)
}

paraSumArrayItems <- function(xa, partitions) {
    .Call('_QPADMslack_paraSumArrayItems', PACKAGE = 'QPADMslack', xa, partitions)
}

invertLongMatrixWithXk <- function(x, p, nk, k) {
    .Call('_QPADMslack_invertLongMatrixWithXk', PACKAGE = 'QPADMslack', x, p, nk, k)
}

invertShortMatrixWithXk <- function(x, p, nk, k) {
    .Call('_QPADMslack_invertShortMatrixWithXk', PACKAGE = 'QPADMslack', x, p, nk, k)
}

paraQPADMslackcpp <- function(y, x, K, tau, penalty, a, lambda, pho = 5, maxstep = 1000L, eps = 0.001, intercept = FALSE) {
    .Call('_QPADMslack_paraQPADMslackcpp', PACKAGE = 'QPADMslack', y, x, K, tau, penalty, a, lambda, pho, maxstep, eps, intercept)
}

threadedparaQPADMslackcpp <- function(y, x, K, tau, penalty, a, lambda, pho = 5, maxstep = 1000L, eps = 0.001, intercept = FALSE) {
    .Call('_QPADMslack_threadedparaQPADMslackcpp', PACKAGE = 'QPADMslack', y, x, K, tau, penalty, a, lambda, pho, maxstep, eps, intercept)
}

threadedSansJoinQPADMslackcpp <- function(y, x, K, tau, penalty, a, lambda, pho = 5, maxstep = 1000L, eps = 0.001, intercept = FALSE) {
    .Call('_QPADMslack_threadedSansJoinQPADMslackcpp', PACKAGE = 'QPADMslack', y, x, K, tau, penalty, a, lambda, pho, maxstep, eps, intercept)
}

asyncQPADMslackcpp <- function(y, x, K, tau, penalty, a, lambda, pho = 5, maxstep = 1000L, eps = 0.001, intercept = FALSE) {
    .Call('_QPADMslack_asyncQPADMslackcpp', PACKAGE = 'QPADMslack', y, x, K, tau, penalty, a, lambda, pho, maxstep, eps, intercept)
}

asyncSansGetQPADMslackcpp <- function(y, x, K, tau, penalty, a, lambda, pho = 5, maxstep = 1000L, eps = 0.001, intercept = FALSE) {
    .Call('_QPADMslack_asyncSansGetQPADMslackcpp', PACKAGE = 'QPADMslack', y, x, K, tau, penalty, a, lambda, pho, maxstep, eps, intercept)
}

